src/mysite_test1/urls.py
from django.conf.urls.defaults import patterns, include, url
from mysite_test1.views import home, hello, current_datetime, hours_ahead, get_pi, display_meta
from mysite_test1.books.views import search

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite_test1.views.home', name='home'),
    # url(r'^mysite_test1/', include('mysite_test1.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    
    (r'^decision_support/', include('mysite_test1.decision_support.urls')),    
    (r'^$', home), 
    (r'^hello/$',hello), # strict match to /hello/
    (r'^time/$',current_datetime), # strict match to /time/
    (r'^time/plus/(\d{1,2})/$',hours_ahead), # calculate time xx hours ahead, limiting hours to 2 digit #s; r = raw input, so non interpreted meta-chars; parens capture data
    (r'^mc/getpi/$',get_pi),
    (r'^meta/$',display_meta), # display meta
    (r'^search/$', search), # book search
)

urlpatterns += patterns('mysite_test1.contact.views',
    (r'^contact/$', 'contact'),
    (r'^contact/thanks/$', 'thanks'),
    (r'^ajax/xhr_test/$', 'xhr_test'),
    (r'^ajax/ajax_test/$', 'ajax_test'),
)

urlpatterns += patterns('mysite_test1.seventools.views',
    (r'^seventools/$', 'createcards'),
    (r'^seventools/cardsession/$', 'createcards'),
    (r'^seventools/cardsession/addsession/$', 'createcards'),
    (r'^seventools/cardsession/json/$', 'session_cards_JSON'),
    (r'^seventools/cardsession/addcard/$', 'add_card'),
    (r'^seventools/cardsession/recallcard/$', 'recall_card'),
    (r'^seventools/cardsession/saveallcards/$', 'saveallcards'),
    (r'^seventools/todo/$', 'todo'),
)

src/mysite_test1/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100) # simple validation
    email = forms.EmailField(required=False, label='Your e-mail address') # required field, custom label
    message = forms.CharField(widget=forms.Textarea) # change the field type
    
    # method run on data after passing default validation
    # name of function indicates applicable field
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

src/mysite_test1/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.template import Context, RequestContext
from django.shortcuts import render_to_response
from mysite_test1.contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
           initial={'subject': 'I love your site!'}
       )
    return render_to_response('contact_form.html', {'form': form})

def thanks(request):
    return render_to_response('contact_thanks_form.html')

def xhr_test(request):
    if request.is_ajax():
        if request.method == 'GET':
            message = "This is an XHR GET request"
        elif request.method == 'POST':
            message = "This is an XHR POST request"
            # Here we can access the POST data
            print request.POST
    else:
        message = "No XHR"
    return HttpResponse(message)

def ajax_test(request):
    return render_to_response('ajax_test.html',
                              {"foo": "bar"},
                              context_instance=RequestContext(request)) # must include context instance to get STATIC_FILES to work

src/mysite_test1/templates/ajax_test.html
<head>
	<script src="{{ STATIC_URL }}js/d3/d3.js" type='text/javascript'></script>
	<script src="{{ STATIC_URL }}js/d3/d3.layout.js" type='text/javascript'> </script>
	<script src="{{ STATIC_URL }}js/jquery-1.7.1.js" type='text/javascript'></script>
	
	<style>
		.chart div {
			font: 10px sans-serif;
			background-color: steelblue;
			text-align: right;
			padding: 3px;
			margin: 1px;
			color: white;
		}
		
		.chart rect {
		  stroke: white;
		  fill: steelblue;
		 }
		
		.node {
		  font: 10px sans-serif;
		}
				  
		.node circle {
		  fill: #fff;
		  stroke: steelblue;
		  stroke-width: 1.5px;
		}
			
		.link {
		  fill: none;
		  stroke: #ccc;
		  stroke-width: 1.5px;
		}
	}
	</style>
</head>
<body>
	<h1>TEST PAGE</h1>

	<p class='gallery1'> Paragraph 1 </p>
	<p class='gallery2'> Paragraph 2 </p>
	<p class='gallery3'> Paragraph 3 </p>
	<p class='gallery4' id='Paragraph4'> Paragraph 4 </p>
	<img src="{{ STATIC_URL }}images/Penguins.jpg" />
	
	<script type='text/javascript'>
		// Note: Can't include in header because hasn't encountered the body tag yet
		var data = [4, 8, 15, 16, 23, 42];
		var chart = d3.select(".gallery1").append("div")
			.attr("class", "chart");
		
		var x = d3.scale.linear()
		    .domain([0, d3.max(data)])
		    .range(["0px", "400px"]);

		chart.selectAll("div")
		    .data(data)
		  .enter().append("div")
		    .style("width", x)
		    .text(String);
	</script>

	<script type='text/javascript'>
		var chart = d3.select(".gallery2").append("svg")
		     .attr("class", "chart")
		     .attr("width", 440)
		     .attr("height", 140)
		   .append("g")
		   	 .attr("transform", "translate(10,15)");
		     
		var x = d3.scale.linear()
		    .domain([0, d3.max(data)])
		    .range([0, 420]);
		    
		var y = d3.scale.ordinal()
		    .domain(data)
		    .rangeBands([0, 120]);

		chart.selectAll("rect")
		    .data(data)
		  .enter().append("rect")
		    .attr("y", y)
		    .attr("width", x)
		    .attr("height", y.rangeBand());

		chart.selectAll("text")
		    .data(data)
		  .enter().append("text")
		  	.attr("x", x)
		    .attr("y", function(d) { return y(d) + y.rangeBand() / 2; })
		    .attr("dx", -3) // padding-right
		    .attr("dy", ".35em") // vertical-align: middle
		    .attr("text-anchor", "end") // text-align: right
		    .text(String);
		    
		chart.selectAll("line")
		    .data(x.ticks(10))
		  .enter().append("line")
		    .attr("x1", x)
		    .attr("x2", x)
		    .attr("y1", 0)
		    .attr("y2", 120)
		    .style("stroke", "#ccc");
		    
		chart.selectAll(".rule")
		    .data(x.ticks(10))
		  .enter().append("text")
		    .attr("class", "rule")
		    .attr("x", x)
		    .attr("y", 0)
		    .attr("dy", -3)
		    .attr("text-anchor", "middle")
		    .text(String);
		    
		chart.append("line")
		    .attr("y1", 0)
		    .attr("y2", 120)
		    .style("stroke", "#000");

	</script>
	<script type='text/javascript'>
		var w = 960,
		    h = 2200;
		
		var cluster = d3.layout.cluster()
		    .size([h, w - 160]);
		
		var diagonal = d3.svg.diagonal()
		    .projection(function(d) { return [d.y, d.x]; });
		
		var vis = d3.select("#Paragraph4").append("svg")
		    .attr("width", w)
		    .attr("height", h)
		  .append("g")
		    .attr("transform", "translate(40, 0)");
		 		
		d3.json("{{ STATIC_URL }}data/flare.json", function(json) {
		  var nodes = cluster.nodes(json);
          		
		  var link = vis.selectAll("path.link")
		      .data(cluster.links(nodes))
		    .enter().append("path")
		      .attr("class", "link")
		      .attr("d", diagonal);
		
		  var node = vis.selectAll("g.node")
		      .data(nodes)
		    .enter().append("g")
		      .attr("class", "node")
		      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; })
		
		  node.append("circle")
		      .attr("r", 4.5);
		
		  node.append("text")
		      .attr("dx", function(d) { return d.children ? -8 : 8; })
		      .attr("dy", 3)
		      .attr("text-anchor", function(d) { return d.children ? "end" : "start"; })
		      .text(function(d) { return d.name; });
		});
	</script>
	
</body>

src/mysite_test1/templates/base_time.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

src/mysite_test1/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field">
            {{ form.message.errors }}
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

src/mysite_test1/templates/createcards.html
<html>
<head>
	<!-- Styling -->
	<link href="{{ STATIC_URL }}css/createcards.css" media="all" rel="stylesheet" type="text/css"/>
	
	<!-- Utility Javascript -->
	<script src="{{ STATIC_URL }}js/jquery-ui-1.8.17.custom/js/jquery-1.7.1.min.js" type='text/javascript'></script>	
	<script src="{{ STATIC_URL }}js/jquery-ui-1.8.17.custom/js/jquery-ui-1.8.17.custom.min.js" type='text/javascript'></script>
	<script src="{{ STATIC_URL }}js/json2.js"></script>
	<script src="{{ STATIC_URL }}js/underscore-1.3.1.js"></script>	
	
	<!-- Visualization Javascript -->
	<script src="{{ STATIC_URL }}js/d3/d3.js" type='text/javascript'></script>
	<script src="{{ STATIC_URL }}js/d3/d3.layout.js" type='text/javascript'> </script>
	<script src="{{ STATIC_URL }}js/jquery.svg/jquery.svg.js" type='text/javascript'></script>
	<script src="{{ STATIC_URL }}js/jquery.svg/jquery.svgdom.js" type='text/javascript'></script>
	
	<!-- Javascript App -->
	<script src="{{ STATIC_URL }}js/createcards.js" type='text/javascript'></script>
	<script>
		// Initialize the app when the document is ready
		$(document).ready(function(){
			cardsession.startapp();
		})
	</script>
</head>
<body>
	<div id="card_entry">
		<h1>Create Cards</h1>
		
		<form id="name_input" action="javascript: var a=1;">
			New card: <input type="text" id="new_card" maxlength = "40" name="newcardname" /><br />
			<input type="submit" value="Submit" />
		</form>
		
		<table id="cards_container"></table>
	</div>
	
	<div id="droppable"></div>
	<h2>Select Session</h2>
	<form id = "session_select">
		<select>
  		{% for session in sessions %}
	  		<option value="{{ session.id }}">{{ session.name }}</option>
		{% endfor %}
		</select>
	</form>
	<button onclick="console.log(cardsession.current_session.getCards())">Save Cards to Database</button>
	<table id="dropped_cards"></table>
	<button onclick="console.log(cardsession.current_session.getCards())">Update SVG</button>
	
</body>
</html>

src/mysite_test1/templates/current_datetime.html
{% extends "base_time.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

src/mysite_test1/templates/decision_support_base.html
<html>
<head>
    <title>{% block title %}Decision Support{% endblock %}</title>
</head>
<body>
    <h1>Decision Support</h1>
	<p>
		This tool uses AHP and TOPSIS to guide decision making.
	</p>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Developed by Timothy Van Heest, Jan 2012</p>
    {% endblock %}
</body>
</html>

src/mysite_test1/templates/decision_support_choices.html
{% extends "decision_support_base.html" %}

{% block title %}Identify Choices{% endblock %}

{% block content %}

    <form action="select_variables/" method="post">
        <input type="text" name="Choice1"><br/>
        <input type="text" name="Choice2"><br/>
        <input type="text" name="Choice3"><br/>
        <input type="submit" value="Next: Identify Factors">
    </form>

{% endblock %}

src/mysite_test1/templates/decision_support_variables.html
{% extends "decision_support_base.html" %}

{% block title %}Identify Variables{% endblock %}

{% block content %}

	<h2>Your Choices were</h2>
	<ol>
		{% for k, v in choices %}
			<li>{{ k }} {{ v }}</li>
		{% endfor %}
	</ol>
	
	<h2>Identify Variables</h2>

    <form action="mappings/" method="post">
        <input type="text" name="Variable1"><br/>
        <input type="text" name="Variable2"><br/>
        <input type="text" name="Variable3"><br/>
        <input type="submit" value="Next: Creatre Mappings">
    </form>

{% endblock %}

src/mysite_test1/templates/getpi.html
{% extends "base_mc.html" %}

{% block title %}Calculate Pi{% endblock %}

{% block content %}
<p>The values pi for of {{ n_trials }} MC trials with {{ n_moves }} moves each are:</p>

{% for pi in pi_list %}
    <p>{{ forloop.counter }}: {{ pi }}</p>
{% endfor %}

{% endblock %}

src/mysite_test1/templates/hours_ahead.html
{% extends "base_time.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

src/mysite_test1/templates/meta_display.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>Meta data from request.META function</title>
</head>
<body>
    <h1>My meta data</h1>
	<table>
	{% for i in html %}
	    <tr>
	    	<td>{{ forloop.counter }}: {{ i }}</td>
		</tr>
	{% endfor %}
	</table>
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

src/mysite_test1/templates/search_form.html
<html>
	<head>
		<title>Search</title>
	</head>
	<body>
		<h1>Look for some books</h1>
		{% if errors %}
			<ul>
				{% for error in errors %}
				<li style="color:red;">{{ error }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		<form action="" method="get">
			<input type="text" name="q" />
			<input type="submit" value="Search" />
		</form>
	</body>
</html>

src/mysite_test1/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}

src/mysite_test1/templates/todo.html
<!DOCTYPE html>
<html>

  <head>
    <title>Backbone Demo: Todos</title>
    <!-- Style -->
    <link href="{{ STATIC_URL }}css/todos.css" media="all" rel="stylesheet" type="text/css"/>
	<!-- Javascript -->
    <script src="{{ STATIC_URL }}js/json2.js"></script>
    <script src="{{ STATIC_URL }}js/jquery-1.7.1.js"></script>
    <script src="{{ STATIC_URL }}js/underscore-1.3.1.js"></script>
    <script src="{{ STATIC_URL }}js/backbone.js"></script>
    <script src="{{ STATIC_URL }}js/backbone-localstorage.js"></script>
    <script src="{{ STATIC_URL }}js/todos.js"></script>
  </head>

  <body>

    <!-- Todo App Interface -->

    <div id="todoapp">

      <div class="title">
        <h1>Todos</h1>
      </div>

      <div class="content">

        <div id="create-todo">

          <input id="new-todo" placeholder="What needs to be done?" type="text" />
          <span class="ui-tooltip-top" style="display:none;">Press Enter to save this task</span>
        </div>

        <div id="todos">
          <ul id="todo-list"></ul>
        </div>

        <div id="todo-stats"></div>

      </div>

    </div>

    <ul id="instructions">
      <li>Double-click to edit a todo.</li>
      <li>See the original <a href="http://documentcloud.github.com/backbone/examples/todos/index.html" target="_blank">here</a></li>
    </ul>

    <!-- Templates -->

    <script type="text/template" id="item-template">
      <div class="todo <%= done ? 'done' : '' %>">
        <div class="display">
          <input class="check" type="checkbox" <%= done ? 'checked="checked"' : '' %> />
          <div class="todo-text"></div>
          <span class="todo-destroy"></span>
        </div>
        <div class="edit">
          <input class="todo-input" type="text" value="" />
        </div>
      </div>
    </script>

    <script type="text/template" id="stats-template">
      <% if (total) { %>
        <span class="todo-count">
          <span class="number"><%= remaining %></span>
          <span class="word"><%= remaining == 1 ? 'item' : 'items' %></span> left.
        </span>
      <% } %>
      <% if (done) { %>
        <span class="todo-clear">
          <a href="#">
            Clear <span class="number-done"><%= done %></span>
            completed <span class="word-done"><%= done == 1 ? 'item' : 'items' %></span>
          </a>
        </span>
      <% } %>
    </script>

  </body>

</html>